/**
 * Generates self-contained Typst markup for a blank (unplotted) coordinate
 * grid that students can draw on.
 *
 * The output deliberately uses only Typst builtins — `box`, `place`, `line`,
 * `polygon`, `text` — so an inserted graph keeps rendering without the
 * `@preview` package downloads the plotted questions rely on.
 */

export interface BlankGraphOptions {
  xMin: number;
  xMax: number;
  yMin: number;
  yMax: number;
  xStep: number;
  yStep: number;
  /** Drawing area in centimetres. */
  width: number;
  height: number;
  showGrid: boolean;
  showNumbers: boolean;
  showArrows: boolean;
  xLabel: string;
  yLabel: string;
}

export const defaultBlankGraphOptions: BlankGraphOptions = {
  xMin: -5,
  xMax: 5,
  yMin: -5,
  yMax: 5,
  xStep: 1,
  yStep: 1,
  width: 7,
  height: 7,
  showGrid: true,
  showNumbers: true,
  showArrows: true,
  xLabel: 'x',
  yLabel: 'y',
};

/** Human-readable reason the options cannot produce a graph, or null if fine. */
export function validateBlankGraphOptions(o: BlankGraphOptions): string | null {
  const finite = [o.xMin, o.xMax, o.yMin, o.yMax, o.xStep, o.yStep, o.width, o.height];
  if (finite.some((v) => !Number.isFinite(v))) return 'All graph values must be numbers.';
  if (o.xMax <= o.xMin) return 'X max must be greater than x min.';
  if (o.yMax <= o.yMin) return 'Y max must be greater than y min.';
  if (o.xStep <= 0 || o.yStep <= 0) return 'Step sizes must be greater than zero.';
  if (o.width <= 0 || o.height <= 0) return 'Width and height must be greater than zero.';
  if ((o.xMax - o.xMin) / o.xStep > 100) return 'X step is too small for this domain (max 100 lines).';
  if ((o.yMax - o.yMin) / o.yStep > 100) return 'Y step is too small for this range (max 100 lines).';
  return null;
}

/** Trim float noise so the emitted source stays readable. */
function num(value: number): string {
  const rounded = Math.round(value * 1e6) / 1e6;
  return Number.isInteger(rounded) ? `${rounded}.0` : `${rounded}`;
}

function typstString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * Build the Typst block for a blank graph. The result is a single expression
 * that can be dropped anywhere in a question body or solution.
 */
export function generateBlankGraphTypst(options: BlankGraphOptions): string {
  const o = { ...defaultBlankGraphOptions, ...options };
  const xLabel = o.xLabel.trim();
  const yLabel = o.yLabel.trim();

  return `#{
  // Blank graph — generated by Test Generator
  let xmin = ${num(o.xMin)}
  let xmax = ${num(o.xMax)}
  let ymin = ${num(o.yMin)}
  let ymax = ${num(o.yMax)}
  let xstep = ${num(o.xStep)}
  let ystep = ${num(o.yStep)}
  let w = ${num(o.width)}cm
  let h = ${num(o.height)}cm
  let show-grid = ${o.showGrid}
  let show-numbers = ${o.showNumbers}
  let show-arrows = ${o.showArrows}

  let sx(x) = w * ((x - xmin) / (xmax - xmin))
  let sy(y) = h * (1.0 - (y - ymin) / (ymax - ymin))
  let clamp(v, lo, hi) = calc.max(lo, calc.min(hi, v))
  // Axes sit on the edge when the origin is outside the visible window.
  let x-axis-y = clamp(0.0, ymin, ymax)
  let y-axis-x = clamp(0.0, xmin, xmax)
  let fmt(v) = {
    let r = calc.round(v, digits: 3)
    if r == calc.round(r) { str(calc.round(r)) } else { str(r) }
  }

  let nx = int(calc.round((xmax - xmin) / xstep))
  let ny = int(calc.round((ymax - ymin) / ystep))
  let grid-stroke = 0.4pt + luma(60%)
  let axis-stroke = 0.8pt + black
  let tick = 3pt

  box(width: w, height: h, stroke: 0.5pt + luma(40%), {
    if show-grid {
      for i in range(nx + 1) {
        let x = sx(xmin + i * xstep)
        place(line(start: (x, 0pt), end: (x, h), stroke: grid-stroke))
      }
      for j in range(ny + 1) {
        let y = sy(ymin + j * ystep)
        place(line(start: (0pt, y), end: (w, y), stroke: grid-stroke))
      }
    }

    place(line(start: (0pt, sy(x-axis-y)), end: (w, sy(x-axis-y)), stroke: axis-stroke))
    place(line(start: (sx(y-axis-x), 0pt), end: (sx(y-axis-x), h), stroke: axis-stroke))

    for i in range(nx + 1) {
      let value = xmin + i * xstep
      let x = sx(value)
      place(line(
        start: (x, sy(x-axis-y) - tick),
        end: (x, sy(x-axis-y) + tick),
        stroke: axis-stroke,
      ))
      if show-numbers and calc.abs(value) > 1e-9 {
        place(
          dx: x - 1cm,
          dy: sy(x-axis-y) + tick,
          box(width: 2cm, align(center, text(size: 7pt, fmt(value)))),
        )
      }
    }

    for j in range(ny + 1) {
      let value = ymin + j * ystep
      let y = sy(value)
      place(line(
        start: (sx(y-axis-x) - tick, y),
        end: (sx(y-axis-x) + tick, y),
        stroke: axis-stroke,
      ))
      if show-numbers and calc.abs(value) > 1e-9 {
        place(
          dx: sx(y-axis-x) - tick - 2cm,
          dy: y - 0.5em,
          box(width: 2cm, align(right, text(size: 7pt, fmt(value)))),
        )
      }
    }

    if show-numbers {
      place(
        dx: sx(y-axis-x) - 2cm - tick,
        dy: sy(x-axis-y) + tick,
        box(width: 2cm, align(right, text(size: 7pt, "0"))),
      )
    }

    if show-arrows {
      let head = 4pt
      place(
        dx: w - head,
        dy: sy(x-axis-y) - head / 2,
        polygon(fill: black, (0pt, 0pt), (head, head / 2), (0pt, head)),
      )
      place(
        dx: sx(y-axis-x) - head / 2,
        dy: 0pt,
        polygon(fill: black, (0pt, head), (head / 2, 0pt), (head, head)),
      )
    }
${xLabel ? `
    place(
      dx: w - 1cm,
      dy: sy(x-axis-y) - 1.2em - tick,
      box(width: 1cm, align(right, text(size: 8pt, style: "italic", ${typstString(xLabel)}))),
    )` : ''}${yLabel ? `
    place(
      dx: sx(y-axis-x) + tick + 2pt,
      dy: 2pt,
      text(size: 8pt, style: "italic", ${typstString(yLabel)}),
    )` : ''}
  })
}`;
}
