// Builds the generator roadmap pages in roadmap/ from the repo's own data:
//   roadmap/manitoba-atlas.html ← src/lib/generator/catalog.ts + outcomes.ts
//   roadmap/kuta-topics.html    ← roadmap/data/kuta-topics.json
// Usage: npm run roadmap:build            (write the pages)
//        npm run roadmap:build -- --check (exit 1 if a page is out of date)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATALOGS } from '../src/lib/generator/catalog.ts';
import { GENERATOR_COURSES, outcomeStatement } from '../src/lib/generator/outcomes.ts';
import { GENERATORS } from '../src/lib/generator/registry.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ROADMAP = join(ROOT, 'roadmap');

function fill(template: string, data: unknown, sources: string): string {
  const html = readFileSync(join(ROADMAP, 'templates', template), 'utf8');
  // Escape `<` so the data can never close the script element.
  const json = JSON.stringify(data).replace(/</g, '\\u003c');
  const note = `<!-- Generated by scripts/build-roadmap.ts from roadmap/templates/${template} and ${sources}. Do not edit; run npm run roadmap:build. -->\n`;
  return html.replace('<!doctype html>\n', `<!doctype html>\n${note}`).replace('__DATA__', () => json);
}

/** The framework document each course's outcomes come from. */
const SOURCES: Record<string, string> = {
  'mb-10f': 'https://www.edu.gov.mb.ca/k12/framework/publications/math/framework_9-12/docs/gr9.pdf',
  'mb-10i': 'https://www.edu.gov.mb.ca/k12/framework/publications/math/framework_9-12/docs/gr10_intro_ap_pc.pdf',
  'mb-30s': 'https://www.edu.gov.mb.ca/k12/framework/publications/math/framework_9-12/docs/gr11_precal.pdf',
  'mb-40s': 'https://www.edu.gov.mb.ca/k12/framework/publications/math/framework_9-12/docs/gr12_precal.pdf',
};

function manitobaData() {
  return CATALOGS.map((catalog) => {
    const course = GENERATOR_COURSES.find((c) => c.id === catalog.classId);
    if (!course) throw new Error(`Catalog for unknown course ${catalog.classId}`);
    return {
      id: course.id,
      name: course.name,
      source: SOURCES[course.id] ?? 'https://www.edu.gov.mb.ca/k12/framework/publications/math/framework_9-12/',
      strands: course.units.map((u) => ({
        id: u.id,
        name: u.name,
        outcomes: u.sections.map((s) => ({ id: s.id, short: s.name, statement: outcomeStatement(s.id) ?? s.name })),
      })),
      // Each problem type notes whether a generator in the app produces it.
      units: catalog.units.map((u) => ({ ...u, types: u.types.map((t) => ({ ...t, generator: GENERATORS.some((g) => g.catalogId === t.id) })) })),
    };
  });
}

function kutaData() {
  const data = JSON.parse(readFileSync(join(ROADMAP, 'data', 'kuta-topics.json'), 'utf8'));
  const titles = new Map(GENERATORS.map((g) => [g.id, g.title]));
  const similar: Record<string, string> = {};
  for (const [key, id] of Object.entries(data.similarGenerators as Record<string, string>)) {
    const title = titles.get(id);
    if (!title) throw new Error(`kuta-topics.json: unknown generator ${id} for ${key}`);
    similar[key] = title;
  }
  return { programs: data.programs, similar };
}

/** The roadmap pages as they should be, keyed by path relative to the repo root. */
export function buildRoadmapPages(): Record<string, string> {
  return {
    'roadmap/manitoba-atlas.html': fill('manitoba-atlas.html', manitobaData(), 'src/lib/generator/catalog.ts'),
    'roadmap/kuta-topics.html': fill('kuta-topics.html', kutaData(), 'roadmap/data/kuta-topics.json'),
  };
}

/** Paths whose committed page differs from a fresh build. */
export function staleRoadmapPages(): string[] {
  return Object.entries(buildRoadmapPages())
    .filter(([path, html]) => {
      try { return readFileSync(join(ROOT, path), 'utf8') !== html; } catch { return true; }
    })
    .map(([path]) => path);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--check')) {
    const stale = staleRoadmapPages();
    if (stale.length) {
      console.error(`Out of date: ${stale.join(', ')}. Run npm run roadmap:build.`);
      process.exit(1);
    }
    console.log('Roadmap pages are up to date.');
  } else {
    for (const [path, html] of Object.entries(buildRoadmapPages())) {
      writeFileSync(join(ROOT, path), html);
      console.log(`Wrote ${path}`);
    }
  }
}
